
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Sep 15 12:07:24 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 48;
  public static final int CONST = 16;
  public static final int GRT = 29;
  public static final int ADDAS = 35;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 21;
  public static final int LESS = 30;
  public static final int FOR = 19;
  public static final int MINUS = 23;
  public static final int GREQ = 31;
  public static final int RPAREN = 7;
  public static final int AND = 33;
  public static final int DIVAS = 38;
  public static final int OR = 34;
  public static final int BOOL = 47;
  public static final int COMMA = 8;
  public static final int CLASS = 14;
  public static final int INC = 40;
  public static final int MODAS = 39;
  public static final int DIV = 25;
  public static final int PLUS = 22;
  public static final int IF = 49;
  public static final int SUBAS = 36;
  public static final int ABSTRACT = 15;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 11;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int NUMBER = 45;
  public static final int MOD = 26;
  public static final int IDENT = 46;
  public static final int BREAK = 13;
  public static final int VOID = 12;
  public static final int LBRACK = 42;
  public static final int ISNEQ = 28;
  public static final int ELSE = 50;
  public static final int LBRACE = 3;
  public static final int POINT = 44;
  public static final int RBRACK = 43;
  public static final int READ = 18;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 20;
  public static final int PROG = 2;
  public static final int LEQ = 32;
  public static final int DEC = 41;
  public static final int MULAS = 37;
  public static final int PRINT = 9;
  public static final int ISEQ = 27;
}

